#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FraudMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RAFMS")]
	public partial class RAFMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccess(Access instance);
    partial void UpdateAccess(Access instance);
    partial void DeleteAccess(Access instance);
    partial void InsertCase(Case instance);
    partial void UpdateCase(Case instance);
    partial void DeleteCase(Case instance);
    partial void Insertcase_line(case_line instance);
    partial void Updatecase_line(case_line instance);
    partial void Deletecase_line(case_line instance);
    partial void InsertCaseStatus(CaseStatus instance);
    partial void UpdateCaseStatus(CaseStatus instance);
    partial void DeleteCaseStatus(CaseStatus instance);
    partial void InsertCity(City instance);
    partial void UpdateCity(City instance);
    partial void DeleteCity(City instance);
    partial void InsertConnectionDomain(ConnectionDomain instance);
    partial void UpdateConnectionDomain(ConnectionDomain instance);
    partial void DeleteConnectionDomain(ConnectionDomain instance);
    partial void InsertFraudStatus(FraudStatus instance);
    partial void UpdateFraudStatus(FraudStatus instance);
    partial void DeleteFraudStatus(FraudStatus instance);
    partial void InsertFraudType(FraudType instance);
    partial void UpdateFraudType(FraudType instance);
    partial void DeleteFraudType(FraudType instance);
    partial void InsertGSM_type(GSM_type instance);
    partial void UpdateGSM_type(GSM_type instance);
    partial void DeleteGSM_type(GSM_type instance);
    partial void InsertNationality(Nationality instance);
    partial void UpdateNationality(Nationality instance);
    partial void DeleteNationality(Nationality instance);
    partial void InsertRegion(Region instance);
    partial void UpdateRegion(Region instance);
    partial void DeleteRegion(Region instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUsersAccess(UsersAccess instance);
    partial void UpdateUsersAccess(UsersAccess instance);
    partial void DeleteUsersAccess(UsersAccess instance);
    #endregion
		
		public RAFMSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RAFMSConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RAFMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RAFMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RAFMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RAFMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Access> Accesses
		{
			get
			{
				return this.GetTable<Access>();
			}
		}
		
		public System.Data.Linq.Table<Case> Cases
		{
			get
			{
				return this.GetTable<Case>();
			}
		}
		
		public System.Data.Linq.Table<case_line> case_lines
		{
			get
			{
				return this.GetTable<case_line>();
			}
		}
		
		public System.Data.Linq.Table<CaseStatus> CaseStatus
		{
			get
			{
				return this.GetTable<CaseStatus>();
			}
		}
		
		public System.Data.Linq.Table<City> Cities
		{
			get
			{
				return this.GetTable<City>();
			}
		}
		
		public System.Data.Linq.Table<ConnectionDomain> ConnectionDomains
		{
			get
			{
				return this.GetTable<ConnectionDomain>();
			}
		}
		
		public System.Data.Linq.Table<FraudStatus> FraudStatus
		{
			get
			{
				return this.GetTable<FraudStatus>();
			}
		}
		
		public System.Data.Linq.Table<FraudType> FraudTypes
		{
			get
			{
				return this.GetTable<FraudType>();
			}
		}
		
		public System.Data.Linq.Table<GSM_type> GSM_types
		{
			get
			{
				return this.GetTable<GSM_type>();
			}
		}
		
		public System.Data.Linq.Table<Nationality> Nationalities
		{
			get
			{
				return this.GetTable<Nationality>();
			}
		}
		
		public System.Data.Linq.Table<Region> Regions
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UsersAccess> UsersAccesses
		{
			get
			{
				return this.GetTable<UsersAccess>();
			}
		}
		
		public System.Data.Linq.Table<Users_vw> Users_vws
		{
			get
			{
				return this.GetTable<Users_vw>();
			}
		}
		
		public System.Data.Linq.Table<Case_vw> Case_vws
		{
			get
			{
				return this.GetTable<Case_vw>();
			}
		}
		
		public System.Data.Linq.Table<CaseStatus_vw> CaseStatus_vws
		{
			get
			{
				return this.GetTable<CaseStatus_vw>();
			}
		}
		
		public System.Data.Linq.Table<Cities_vw> Cities_vws
		{
			get
			{
				return this.GetTable<Cities_vw>();
			}
		}
		
		public System.Data.Linq.Table<ConnectionDomains_vw> ConnectionDomains_vws
		{
			get
			{
				return this.GetTable<ConnectionDomains_vw>();
			}
		}
		
		public System.Data.Linq.Table<FraudStatus_vw> FraudStatus_vws
		{
			get
			{
				return this.GetTable<FraudStatus_vw>();
			}
		}
		
		public System.Data.Linq.Table<FraudTypes_vw> FraudTypes_vws
		{
			get
			{
				return this.GetTable<FraudTypes_vw>();
			}
		}
		
		public System.Data.Linq.Table<GSM_vw> GSM_vws
		{
			get
			{
				return this.GetTable<GSM_vw>();
			}
		}
		
		public System.Data.Linq.Table<Nationality_vw> Nationality_vws
		{
			get
			{
				return this.GetTable<Nationality_vw>();
			}
		}
		
		public System.Data.Linq.Table<Regions_vw> Regions_vws
		{
			get
			{
				return this.GetTable<Regions_vw>();
			}
		}
		
		public System.Data.Linq.Table<case_line_vw> case_line_vws
		{
			get
			{
				return this.GetTable<case_line_vw>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Access")]
	public partial class Access : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _access_id;
		
		private string _access_name;
		
		private EntitySet<UsersAccess> _UsersAccesses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaccess_idChanging(short value);
    partial void Onaccess_idChanged();
    partial void Onaccess_nameChanging(string value);
    partial void Onaccess_nameChanged();
    #endregion
		
		public Access()
		{
			this._UsersAccesses = new EntitySet<UsersAccess>(new Action<UsersAccess>(this.attach_UsersAccesses), new Action<UsersAccess>(this.detach_UsersAccesses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short access_id
		{
			get
			{
				return this._access_id;
			}
			set
			{
				if ((this._access_id != value))
				{
					this.Onaccess_idChanging(value);
					this.SendPropertyChanging();
					this._access_id = value;
					this.SendPropertyChanged("access_id");
					this.Onaccess_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string access_name
		{
			get
			{
				return this._access_name;
			}
			set
			{
				if ((this._access_name != value))
				{
					this.Onaccess_nameChanging(value);
					this.SendPropertyChanging();
					this._access_name = value;
					this.SendPropertyChanged("access_name");
					this.Onaccess_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Access_UsersAccess", Storage="_UsersAccesses", ThisKey="access_id", OtherKey="access_id")]
		public EntitySet<UsersAccess> UsersAccesses
		{
			get
			{
				return this._UsersAccesses;
			}
			set
			{
				this._UsersAccesses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UsersAccesses(UsersAccess entity)
		{
			this.SendPropertyChanging();
			entity.Access = this;
		}
		
		private void detach_UsersAccesses(UsersAccess entity)
		{
			this.SendPropertyChanging();
			entity.Access = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Case]")]
	public partial class Case : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _case_id;
		
		private string _case_customer_name;
		
		private string _case_ID_number;
		
		private System.Nullable<long> _case_customer_number;
		
		private System.Nullable<short> _case_bill_cycle;
		
		private System.Nullable<System.DateTime> _case_bill_date;
		
		private System.Nullable<int> _case_credit_limit;
		
		private System.Nullable<System.DateTime> _case_date;
		
		private string _case_hijri;
		
		private string _case_comment;
		
		private System.Nullable<byte> _case_status;
		
		private string _case_source;
		
		private System.Nullable<short> _case_nationality_id;
		
		private System.Nullable<byte> _case_fraudStatus_id;
		
		private System.Nullable<int> _case_region;
		
		private string _case_city;
		
		private System.Nullable<decimal> _case_estimated_loss;
		
		private System.Nullable<decimal> _case_actual_loss;
		
		private string _case_bill_hdate;
		
		private string _case_billing_user2;
		
		private System.Nullable<int> _case_disconnected_numbers_count;
		
		private System.Nullable<bool> _bulk_insertion;
		
		private System.Nullable<System.DateTime> _case_Activate_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncase_idChanging(long value);
    partial void Oncase_idChanged();
    partial void Oncase_customer_nameChanging(string value);
    partial void Oncase_customer_nameChanged();
    partial void Oncase_ID_numberChanging(string value);
    partial void Oncase_ID_numberChanged();
    partial void Oncase_customer_numberChanging(System.Nullable<long> value);
    partial void Oncase_customer_numberChanged();
    partial void Oncase_bill_cycleChanging(System.Nullable<short> value);
    partial void Oncase_bill_cycleChanged();
    partial void Oncase_bill_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncase_bill_dateChanged();
    partial void Oncase_credit_limitChanging(System.Nullable<int> value);
    partial void Oncase_credit_limitChanged();
    partial void Oncase_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncase_dateChanged();
    partial void Oncase_hijriChanging(string value);
    partial void Oncase_hijriChanged();
    partial void Oncase_commentChanging(string value);
    partial void Oncase_commentChanged();
    partial void Oncase_statusChanging(System.Nullable<byte> value);
    partial void Oncase_statusChanged();
    partial void Oncase_sourceChanging(string value);
    partial void Oncase_sourceChanged();
    partial void Oncase_nationality_idChanging(System.Nullable<short> value);
    partial void Oncase_nationality_idChanged();
    partial void Oncase_fraudStatus_idChanging(System.Nullable<byte> value);
    partial void Oncase_fraudStatus_idChanged();
    partial void Oncase_regionChanging(System.Nullable<int> value);
    partial void Oncase_regionChanged();
    partial void Oncase_cityChanging(string value);
    partial void Oncase_cityChanged();
    partial void Oncase_estimated_lossChanging(System.Nullable<decimal> value);
    partial void Oncase_estimated_lossChanged();
    partial void Oncase_actual_lossChanging(System.Nullable<decimal> value);
    partial void Oncase_actual_lossChanged();
    partial void Oncase_bill_hdateChanging(string value);
    partial void Oncase_bill_hdateChanged();
    partial void Oncase_billing_user2Changing(string value);
    partial void Oncase_billing_user2Changed();
    partial void Oncase_disconnected_numbers_countChanging(System.Nullable<int> value);
    partial void Oncase_disconnected_numbers_countChanged();
    partial void Onbulk_insertionChanging(System.Nullable<bool> value);
    partial void Onbulk_insertionChanged();
    partial void Oncase_Activate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncase_Activate_dateChanged();
    #endregion
		
		public Case()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this.Oncase_idChanging(value);
					this.SendPropertyChanging();
					this._case_id = value;
					this.SendPropertyChanged("case_id");
					this.Oncase_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_customer_name", DbType="NVarChar(200)")]
		public string case_customer_name
		{
			get
			{
				return this._case_customer_name;
			}
			set
			{
				if ((this._case_customer_name != value))
				{
					this.Oncase_customer_nameChanging(value);
					this.SendPropertyChanging();
					this._case_customer_name = value;
					this.SendPropertyChanged("case_customer_name");
					this.Oncase_customer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_ID_number", DbType="NVarChar(200)")]
		public string case_ID_number
		{
			get
			{
				return this._case_ID_number;
			}
			set
			{
				if ((this._case_ID_number != value))
				{
					this.Oncase_ID_numberChanging(value);
					this.SendPropertyChanging();
					this._case_ID_number = value;
					this.SendPropertyChanged("case_ID_number");
					this.Oncase_ID_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_customer_number", DbType="BigInt")]
		public System.Nullable<long> case_customer_number
		{
			get
			{
				return this._case_customer_number;
			}
			set
			{
				if ((this._case_customer_number != value))
				{
					this.Oncase_customer_numberChanging(value);
					this.SendPropertyChanging();
					this._case_customer_number = value;
					this.SendPropertyChanged("case_customer_number");
					this.Oncase_customer_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_cycle", DbType="SmallInt")]
		public System.Nullable<short> case_bill_cycle
		{
			get
			{
				return this._case_bill_cycle;
			}
			set
			{
				if ((this._case_bill_cycle != value))
				{
					this.Oncase_bill_cycleChanging(value);
					this.SendPropertyChanging();
					this._case_bill_cycle = value;
					this.SendPropertyChanged("case_bill_cycle");
					this.Oncase_bill_cycleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_bill_date
		{
			get
			{
				return this._case_bill_date;
			}
			set
			{
				if ((this._case_bill_date != value))
				{
					this.Oncase_bill_dateChanging(value);
					this.SendPropertyChanging();
					this._case_bill_date = value;
					this.SendPropertyChanged("case_bill_date");
					this.Oncase_bill_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_credit_limit", DbType="Int")]
		public System.Nullable<int> case_credit_limit
		{
			get
			{
				return this._case_credit_limit;
			}
			set
			{
				if ((this._case_credit_limit != value))
				{
					this.Oncase_credit_limitChanging(value);
					this.SendPropertyChanging();
					this._case_credit_limit = value;
					this.SendPropertyChanged("case_credit_limit");
					this.Oncase_credit_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_date
		{
			get
			{
				return this._case_date;
			}
			set
			{
				if ((this._case_date != value))
				{
					this.Oncase_dateChanging(value);
					this.SendPropertyChanging();
					this._case_date = value;
					this.SendPropertyChanged("case_date");
					this.Oncase_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_hijri", DbType="NVarChar(200)")]
		public string case_hijri
		{
			get
			{
				return this._case_hijri;
			}
			set
			{
				if ((this._case_hijri != value))
				{
					this.Oncase_hijriChanging(value);
					this.SendPropertyChanging();
					this._case_hijri = value;
					this.SendPropertyChanged("case_hijri");
					this.Oncase_hijriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_comment", DbType="NVarChar(MAX)")]
		public string case_comment
		{
			get
			{
				return this._case_comment;
			}
			set
			{
				if ((this._case_comment != value))
				{
					this.Oncase_commentChanging(value);
					this.SendPropertyChanging();
					this._case_comment = value;
					this.SendPropertyChanged("case_comment");
					this.Oncase_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_status", DbType="TinyInt")]
		public System.Nullable<byte> case_status
		{
			get
			{
				return this._case_status;
			}
			set
			{
				if ((this._case_status != value))
				{
					this.Oncase_statusChanging(value);
					this.SendPropertyChanging();
					this._case_status = value;
					this.SendPropertyChanged("case_status");
					this.Oncase_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_source", DbType="NVarChar(200)")]
		public string case_source
		{
			get
			{
				return this._case_source;
			}
			set
			{
				if ((this._case_source != value))
				{
					this.Oncase_sourceChanging(value);
					this.SendPropertyChanging();
					this._case_source = value;
					this.SendPropertyChanged("case_source");
					this.Oncase_sourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_nationality_id", DbType="SmallInt")]
		public System.Nullable<short> case_nationality_id
		{
			get
			{
				return this._case_nationality_id;
			}
			set
			{
				if ((this._case_nationality_id != value))
				{
					this.Oncase_nationality_idChanging(value);
					this.SendPropertyChanging();
					this._case_nationality_id = value;
					this.SendPropertyChanged("case_nationality_id");
					this.Oncase_nationality_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_fraudStatus_id", DbType="TinyInt")]
		public System.Nullable<byte> case_fraudStatus_id
		{
			get
			{
				return this._case_fraudStatus_id;
			}
			set
			{
				if ((this._case_fraudStatus_id != value))
				{
					this.Oncase_fraudStatus_idChanging(value);
					this.SendPropertyChanging();
					this._case_fraudStatus_id = value;
					this.SendPropertyChanged("case_fraudStatus_id");
					this.Oncase_fraudStatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_region", DbType="Int")]
		public System.Nullable<int> case_region
		{
			get
			{
				return this._case_region;
			}
			set
			{
				if ((this._case_region != value))
				{
					this.Oncase_regionChanging(value);
					this.SendPropertyChanging();
					this._case_region = value;
					this.SendPropertyChanged("case_region");
					this.Oncase_regionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_city", DbType="NVarChar(200)")]
		public string case_city
		{
			get
			{
				return this._case_city;
			}
			set
			{
				if ((this._case_city != value))
				{
					this.Oncase_cityChanging(value);
					this.SendPropertyChanging();
					this._case_city = value;
					this.SendPropertyChanged("case_city");
					this.Oncase_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_estimated_loss", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> case_estimated_loss
		{
			get
			{
				return this._case_estimated_loss;
			}
			set
			{
				if ((this._case_estimated_loss != value))
				{
					this.Oncase_estimated_lossChanging(value);
					this.SendPropertyChanging();
					this._case_estimated_loss = value;
					this.SendPropertyChanged("case_estimated_loss");
					this.Oncase_estimated_lossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_actual_loss", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> case_actual_loss
		{
			get
			{
				return this._case_actual_loss;
			}
			set
			{
				if ((this._case_actual_loss != value))
				{
					this.Oncase_actual_lossChanging(value);
					this.SendPropertyChanging();
					this._case_actual_loss = value;
					this.SendPropertyChanged("case_actual_loss");
					this.Oncase_actual_lossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_hdate", DbType="NVarChar(200)")]
		public string case_bill_hdate
		{
			get
			{
				return this._case_bill_hdate;
			}
			set
			{
				if ((this._case_bill_hdate != value))
				{
					this.Oncase_bill_hdateChanging(value);
					this.SendPropertyChanging();
					this._case_bill_hdate = value;
					this.SendPropertyChanged("case_bill_hdate");
					this.Oncase_bill_hdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_billing_user2", DbType="NVarChar(200)")]
		public string case_billing_user2
		{
			get
			{
				return this._case_billing_user2;
			}
			set
			{
				if ((this._case_billing_user2 != value))
				{
					this.Oncase_billing_user2Changing(value);
					this.SendPropertyChanging();
					this._case_billing_user2 = value;
					this.SendPropertyChanged("case_billing_user2");
					this.Oncase_billing_user2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_disconnected_numbers_count", DbType="Int")]
		public System.Nullable<int> case_disconnected_numbers_count
		{
			get
			{
				return this._case_disconnected_numbers_count;
			}
			set
			{
				if ((this._case_disconnected_numbers_count != value))
				{
					this.Oncase_disconnected_numbers_countChanging(value);
					this.SendPropertyChanging();
					this._case_disconnected_numbers_count = value;
					this.SendPropertyChanged("case_disconnected_numbers_count");
					this.Oncase_disconnected_numbers_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bulk_insertion", DbType="Bit")]
		public System.Nullable<bool> bulk_insertion
		{
			get
			{
				return this._bulk_insertion;
			}
			set
			{
				if ((this._bulk_insertion != value))
				{
					this.Onbulk_insertionChanging(value);
					this.SendPropertyChanging();
					this._bulk_insertion = value;
					this.SendPropertyChanged("bulk_insertion");
					this.Onbulk_insertionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_Activate_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_Activate_date
		{
			get
			{
				return this._case_Activate_date;
			}
			set
			{
				if ((this._case_Activate_date != value))
				{
					this.Oncase_Activate_dateChanging(value);
					this.SendPropertyChanging();
					this._case_Activate_date = value;
					this.SendPropertyChanged("case_Activate_date");
					this.Oncase_Activate_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.case_line")]
	public partial class case_line : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _service_no;
		
		private System.Nullable<long> _account_no;
		
		private System.Nullable<decimal> _amount;
		
		private System.Nullable<long> _case_id;
		
		private System.Nullable<byte> _case_gsm_id;
		
		private System.Nullable<short> _case_fraudType_id;
		
		private System.Nullable<short> _case_user_id;
		
		private string _case_line_billing_user;
		
		private long _case_line_id;
		
		private System.Nullable<System.DateTime> _case_line_date;
		
		private string _case_line_hijri;
		
		private System.Nullable<System.DateTime> _case_line_activate_date;
		
		private System.Nullable<short> _case_line_connection_domain;
		
		private string _case_line_descreption;
		
		private string _case_line_note_intractive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onservice_noChanging(long value);
    partial void Onservice_noChanged();
    partial void Onaccount_noChanging(System.Nullable<long> value);
    partial void Onaccount_noChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void Oncase_idChanging(System.Nullable<long> value);
    partial void Oncase_idChanged();
    partial void Oncase_gsm_idChanging(System.Nullable<byte> value);
    partial void Oncase_gsm_idChanged();
    partial void Oncase_fraudType_idChanging(System.Nullable<short> value);
    partial void Oncase_fraudType_idChanged();
    partial void Oncase_user_idChanging(System.Nullable<short> value);
    partial void Oncase_user_idChanged();
    partial void Oncase_line_billing_userChanging(string value);
    partial void Oncase_line_billing_userChanged();
    partial void Oncase_line_idChanging(long value);
    partial void Oncase_line_idChanged();
    partial void Oncase_line_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncase_line_dateChanged();
    partial void Oncase_line_hijriChanging(string value);
    partial void Oncase_line_hijriChanged();
    partial void Oncase_line_activate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncase_line_activate_dateChanged();
    partial void Oncase_line_connection_domainChanging(System.Nullable<short> value);
    partial void Oncase_line_connection_domainChanged();
    partial void Oncase_line_descreptionChanging(string value);
    partial void Oncase_line_descreptionChanged();
    partial void Oncase_line_note_intractiveChanging(string value);
    partial void Oncase_line_note_intractiveChanged();
    #endregion
		
		public case_line()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_no", DbType="BigInt NOT NULL")]
		public long service_no
		{
			get
			{
				return this._service_no;
			}
			set
			{
				if ((this._service_no != value))
				{
					this.Onservice_noChanging(value);
					this.SendPropertyChanging();
					this._service_no = value;
					this.SendPropertyChanged("service_no");
					this.Onservice_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_no", DbType="BigInt")]
		public System.Nullable<long> account_no
		{
			get
			{
				return this._account_no;
			}
			set
			{
				if ((this._account_no != value))
				{
					this.Onaccount_noChanging(value);
					this.SendPropertyChanging();
					this._account_no = value;
					this.SendPropertyChanged("account_no");
					this.Onaccount_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", DbType="BigInt")]
		public System.Nullable<long> case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this.Oncase_idChanging(value);
					this.SendPropertyChanging();
					this._case_id = value;
					this.SendPropertyChanged("case_id");
					this.Oncase_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_gsm_id", DbType="TinyInt")]
		public System.Nullable<byte> case_gsm_id
		{
			get
			{
				return this._case_gsm_id;
			}
			set
			{
				if ((this._case_gsm_id != value))
				{
					this.Oncase_gsm_idChanging(value);
					this.SendPropertyChanging();
					this._case_gsm_id = value;
					this.SendPropertyChanged("case_gsm_id");
					this.Oncase_gsm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_fraudType_id", DbType="SmallInt")]
		public System.Nullable<short> case_fraudType_id
		{
			get
			{
				return this._case_fraudType_id;
			}
			set
			{
				if ((this._case_fraudType_id != value))
				{
					this.Oncase_fraudType_idChanging(value);
					this.SendPropertyChanging();
					this._case_fraudType_id = value;
					this.SendPropertyChanged("case_fraudType_id");
					this.Oncase_fraudType_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_user_id", DbType="SmallInt")]
		public System.Nullable<short> case_user_id
		{
			get
			{
				return this._case_user_id;
			}
			set
			{
				if ((this._case_user_id != value))
				{
					this.Oncase_user_idChanging(value);
					this.SendPropertyChanging();
					this._case_user_id = value;
					this.SendPropertyChanged("case_user_id");
					this.Oncase_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_billing_user", DbType="NChar(100)")]
		public string case_line_billing_user
		{
			get
			{
				return this._case_line_billing_user;
			}
			set
			{
				if ((this._case_line_billing_user != value))
				{
					this.Oncase_line_billing_userChanging(value);
					this.SendPropertyChanging();
					this._case_line_billing_user = value;
					this.SendPropertyChanged("case_line_billing_user");
					this.Oncase_line_billing_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long case_line_id
		{
			get
			{
				return this._case_line_id;
			}
			set
			{
				if ((this._case_line_id != value))
				{
					this.Oncase_line_idChanging(value);
					this.SendPropertyChanging();
					this._case_line_id = value;
					this.SendPropertyChanged("case_line_id");
					this.Oncase_line_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> case_line_date
		{
			get
			{
				return this._case_line_date;
			}
			set
			{
				if ((this._case_line_date != value))
				{
					this.Oncase_line_dateChanging(value);
					this.SendPropertyChanging();
					this._case_line_date = value;
					this.SendPropertyChanged("case_line_date");
					this.Oncase_line_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_hijri", DbType="NVarChar(200)")]
		public string case_line_hijri
		{
			get
			{
				return this._case_line_hijri;
			}
			set
			{
				if ((this._case_line_hijri != value))
				{
					this.Oncase_line_hijriChanging(value);
					this.SendPropertyChanging();
					this._case_line_hijri = value;
					this.SendPropertyChanged("case_line_hijri");
					this.Oncase_line_hijriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_activate_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> case_line_activate_date
		{
			get
			{
				return this._case_line_activate_date;
			}
			set
			{
				if ((this._case_line_activate_date != value))
				{
					this.Oncase_line_activate_dateChanging(value);
					this.SendPropertyChanging();
					this._case_line_activate_date = value;
					this.SendPropertyChanged("case_line_activate_date");
					this.Oncase_line_activate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_connection_domain", DbType="SmallInt")]
		public System.Nullable<short> case_line_connection_domain
		{
			get
			{
				return this._case_line_connection_domain;
			}
			set
			{
				if ((this._case_line_connection_domain != value))
				{
					this.Oncase_line_connection_domainChanging(value);
					this.SendPropertyChanging();
					this._case_line_connection_domain = value;
					this.SendPropertyChanged("case_line_connection_domain");
					this.Oncase_line_connection_domainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_descreption", DbType="NVarChar(2000)")]
		public string case_line_descreption
		{
			get
			{
				return this._case_line_descreption;
			}
			set
			{
				if ((this._case_line_descreption != value))
				{
					this.Oncase_line_descreptionChanging(value);
					this.SendPropertyChanging();
					this._case_line_descreption = value;
					this.SendPropertyChanged("case_line_descreption");
					this.Oncase_line_descreptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_note_intractive", DbType="NVarChar(2000)")]
		public string case_line_note_intractive
		{
			get
			{
				return this._case_line_note_intractive;
			}
			set
			{
				if ((this._case_line_note_intractive != value))
				{
					this.Oncase_line_note_intractiveChanging(value);
					this.SendPropertyChanging();
					this._case_line_note_intractive = value;
					this.SendPropertyChanged("case_line_note_intractive");
					this.Oncase_line_note_intractiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaseStatus")]
	public partial class CaseStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _caseStatus_id;
		
		private string _caseStatus_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncaseStatus_idChanging(byte value);
    partial void OncaseStatus_idChanged();
    partial void OncaseStatus_nameChanging(string value);
    partial void OncaseStatus_nameChanged();
    #endregion
		
		public CaseStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caseStatus_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte caseStatus_id
		{
			get
			{
				return this._caseStatus_id;
			}
			set
			{
				if ((this._caseStatus_id != value))
				{
					this.OncaseStatus_idChanging(value);
					this.SendPropertyChanging();
					this._caseStatus_id = value;
					this.SendPropertyChanged("caseStatus_id");
					this.OncaseStatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caseStatus_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string caseStatus_name
		{
			get
			{
				return this._caseStatus_name;
			}
			set
			{
				if ((this._caseStatus_name != value))
				{
					this.OncaseStatus_nameChanging(value);
					this.SendPropertyChanging();
					this._caseStatus_name = value;
					this.SendPropertyChanged("caseStatus_name");
					this.OncaseStatus_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cities")]
	public partial class City : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public City()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConnectionDomains")]
	public partial class ConnectionDomain : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public ConnectionDomain()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FraudStatus")]
	public partial class FraudStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _fraudStatus_id;
		
		private string _fraudStatus_name;
		
		private bool _fraudStatus_active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfraudStatus_idChanging(byte value);
    partial void OnfraudStatus_idChanged();
    partial void OnfraudStatus_nameChanging(string value);
    partial void OnfraudStatus_nameChanged();
    partial void OnfraudStatus_activeChanging(bool value);
    partial void OnfraudStatus_activeChanged();
    #endregion
		
		public FraudStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte fraudStatus_id
		{
			get
			{
				return this._fraudStatus_id;
			}
			set
			{
				if ((this._fraudStatus_id != value))
				{
					this.OnfraudStatus_idChanging(value);
					this.SendPropertyChanging();
					this._fraudStatus_id = value;
					this.SendPropertyChanged("fraudStatus_id");
					this.OnfraudStatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string fraudStatus_name
		{
			get
			{
				return this._fraudStatus_name;
			}
			set
			{
				if ((this._fraudStatus_name != value))
				{
					this.OnfraudStatus_nameChanging(value);
					this.SendPropertyChanging();
					this._fraudStatus_name = value;
					this.SendPropertyChanged("fraudStatus_name");
					this.OnfraudStatus_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_active", DbType="Bit NOT NULL")]
		public bool fraudStatus_active
		{
			get
			{
				return this._fraudStatus_active;
			}
			set
			{
				if ((this._fraudStatus_active != value))
				{
					this.OnfraudStatus_activeChanging(value);
					this.SendPropertyChanging();
					this._fraudStatus_active = value;
					this.SendPropertyChanged("fraudStatus_active");
					this.OnfraudStatus_activeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FraudTypes")]
	public partial class FraudType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _fraudType_id;
		
		private string _fraudType_name;
		
		private bool _fraudType_active;
		
		private string _fraudType_desc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfraudType_idChanging(short value);
    partial void OnfraudType_idChanged();
    partial void OnfraudType_nameChanging(string value);
    partial void OnfraudType_nameChanged();
    partial void OnfraudType_activeChanging(bool value);
    partial void OnfraudType_activeChanged();
    partial void OnfraudType_descChanging(string value);
    partial void OnfraudType_descChanged();
    #endregion
		
		public FraudType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short fraudType_id
		{
			get
			{
				return this._fraudType_id;
			}
			set
			{
				if ((this._fraudType_id != value))
				{
					this.OnfraudType_idChanging(value);
					this.SendPropertyChanging();
					this._fraudType_id = value;
					this.SendPropertyChanged("fraudType_id");
					this.OnfraudType_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string fraudType_name
		{
			get
			{
				return this._fraudType_name;
			}
			set
			{
				if ((this._fraudType_name != value))
				{
					this.OnfraudType_nameChanging(value);
					this.SendPropertyChanging();
					this._fraudType_name = value;
					this.SendPropertyChanged("fraudType_name");
					this.OnfraudType_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_active", DbType="Bit NOT NULL")]
		public bool fraudType_active
		{
			get
			{
				return this._fraudType_active;
			}
			set
			{
				if ((this._fraudType_active != value))
				{
					this.OnfraudType_activeChanging(value);
					this.SendPropertyChanging();
					this._fraudType_active = value;
					this.SendPropertyChanged("fraudType_active");
					this.OnfraudType_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_desc", DbType="NVarChar(MAX)")]
		public string fraudType_desc
		{
			get
			{
				return this._fraudType_desc;
			}
			set
			{
				if ((this._fraudType_desc != value))
				{
					this.OnfraudType_descChanging(value);
					this.SendPropertyChanging();
					this._fraudType_desc = value;
					this.SendPropertyChanged("fraudType_desc");
					this.OnfraudType_descChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GSM_types")]
	public partial class GSM_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _gsm_id;
		
		private string _gsm_name;
		
		private bool _gsm_active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongsm_idChanging(byte value);
    partial void Ongsm_idChanged();
    partial void Ongsm_nameChanging(string value);
    partial void Ongsm_nameChanged();
    partial void Ongsm_activeChanging(bool value);
    partial void Ongsm_activeChanged();
    #endregion
		
		public GSM_type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte gsm_id
		{
			get
			{
				return this._gsm_id;
			}
			set
			{
				if ((this._gsm_id != value))
				{
					this.Ongsm_idChanging(value);
					this.SendPropertyChanging();
					this._gsm_id = value;
					this.SendPropertyChanged("gsm_id");
					this.Ongsm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string gsm_name
		{
			get
			{
				return this._gsm_name;
			}
			set
			{
				if ((this._gsm_name != value))
				{
					this.Ongsm_nameChanging(value);
					this.SendPropertyChanging();
					this._gsm_name = value;
					this.SendPropertyChanged("gsm_name");
					this.Ongsm_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_active", DbType="Bit NOT NULL")]
		public bool gsm_active
		{
			get
			{
				return this._gsm_active;
			}
			set
			{
				if ((this._gsm_active != value))
				{
					this.Ongsm_activeChanging(value);
					this.SendPropertyChanging();
					this._gsm_active = value;
					this.SendPropertyChanged("gsm_active");
					this.Ongsm_activeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nationality")]
	public partial class Nationality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _nationality_id;
		
		private string _nationality_name;
		
		private bool _nationality_active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnationality_idChanging(short value);
    partial void Onnationality_idChanged();
    partial void Onnationality_nameChanging(string value);
    partial void Onnationality_nameChanged();
    partial void Onnationality_activeChanging(bool value);
    partial void Onnationality_activeChanged();
    #endregion
		
		public Nationality()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short nationality_id
		{
			get
			{
				return this._nationality_id;
			}
			set
			{
				if ((this._nationality_id != value))
				{
					this.Onnationality_idChanging(value);
					this.SendPropertyChanging();
					this._nationality_id = value;
					this.SendPropertyChanged("nationality_id");
					this.Onnationality_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string nationality_name
		{
			get
			{
				return this._nationality_name;
			}
			set
			{
				if ((this._nationality_name != value))
				{
					this.Onnationality_nameChanging(value);
					this.SendPropertyChanging();
					this._nationality_name = value;
					this.SendPropertyChanged("nationality_name");
					this.Onnationality_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_active", DbType="Bit NOT NULL")]
		public bool nationality_active
		{
			get
			{
				return this._nationality_active;
			}
			set
			{
				if ((this._nationality_active != value))
				{
					this.Onnationality_activeChanging(value);
					this.SendPropertyChanging();
					this._nationality_active = value;
					this.SendPropertyChanged("nationality_active");
					this.Onnationality_activeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regions")]
	public partial class Region : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Region()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _user_id;
		
		private string _user_name;
		
		private string _user_login;
		
		private string _user_password;
		
		private string _user_email;
		
		private bool _user_active;
		
		private System.DateTime _user_create_date;
		
		private System.Nullable<System.DateTime> _user_last_login;
		
		private System.Nullable<bool> _user_last_login_state;
		
		private System.Nullable<bool> _user_level;
		
		private string _user_nikira_user_id;
		
		private EntitySet<UsersAccess> _UsersAccesses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(short value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_loginChanging(string value);
    partial void Onuser_loginChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_activeChanging(bool value);
    partial void Onuser_activeChanged();
    partial void Onuser_create_dateChanging(System.DateTime value);
    partial void Onuser_create_dateChanged();
    partial void Onuser_last_loginChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_last_loginChanged();
    partial void Onuser_last_login_stateChanging(System.Nullable<bool> value);
    partial void Onuser_last_login_stateChanged();
    partial void Onuser_levelChanging(System.Nullable<bool> value);
    partial void Onuser_levelChanged();
    partial void Onuser_nikira_user_idChanging(string value);
    partial void Onuser_nikira_user_idChanged();
    #endregion
		
		public User()
		{
			this._UsersAccesses = new EntitySet<UsersAccess>(new Action<UsersAccess>(this.attach_UsersAccesses), new Action<UsersAccess>(this.detach_UsersAccesses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_login", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string user_login
		{
			get
			{
				return this._user_login;
			}
			set
			{
				if ((this._user_login != value))
				{
					this.Onuser_loginChanging(value);
					this.SendPropertyChanging();
					this._user_login = value;
					this.SendPropertyChanged("user_login");
					this.Onuser_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(250)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(100)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_active", DbType="Bit NOT NULL")]
		public bool user_active
		{
			get
			{
				return this._user_active;
			}
			set
			{
				if ((this._user_active != value))
				{
					this.Onuser_activeChanging(value);
					this.SendPropertyChanging();
					this._user_active = value;
					this.SendPropertyChanged("user_active");
					this.Onuser_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_create_date", DbType="SmallDateTime NOT NULL")]
		public System.DateTime user_create_date
		{
			get
			{
				return this._user_create_date;
			}
			set
			{
				if ((this._user_create_date != value))
				{
					this.Onuser_create_dateChanging(value);
					this.SendPropertyChanging();
					this._user_create_date = value;
					this.SendPropertyChanged("user_create_date");
					this.Onuser_create_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_last_login", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> user_last_login
		{
			get
			{
				return this._user_last_login;
			}
			set
			{
				if ((this._user_last_login != value))
				{
					this.Onuser_last_loginChanging(value);
					this.SendPropertyChanging();
					this._user_last_login = value;
					this.SendPropertyChanged("user_last_login");
					this.Onuser_last_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_last_login_state", DbType="Bit")]
		public System.Nullable<bool> user_last_login_state
		{
			get
			{
				return this._user_last_login_state;
			}
			set
			{
				if ((this._user_last_login_state != value))
				{
					this.Onuser_last_login_stateChanging(value);
					this.SendPropertyChanging();
					this._user_last_login_state = value;
					this.SendPropertyChanged("user_last_login_state");
					this.Onuser_last_login_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_level", DbType="Bit")]
		public System.Nullable<bool> user_level
		{
			get
			{
				return this._user_level;
			}
			set
			{
				if ((this._user_level != value))
				{
					this.Onuser_levelChanging(value);
					this.SendPropertyChanging();
					this._user_level = value;
					this.SendPropertyChanged("user_level");
					this.Onuser_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_nikira_user_id", DbType="NVarChar(255)")]
		public string user_nikira_user_id
		{
			get
			{
				return this._user_nikira_user_id;
			}
			set
			{
				if ((this._user_nikira_user_id != value))
				{
					this.Onuser_nikira_user_idChanging(value);
					this.SendPropertyChanging();
					this._user_nikira_user_id = value;
					this.SendPropertyChanged("user_nikira_user_id");
					this.Onuser_nikira_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UsersAccess", Storage="_UsersAccesses", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<UsersAccess> UsersAccesses
		{
			get
			{
				return this._UsersAccesses;
			}
			set
			{
				this._UsersAccesses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UsersAccesses(UsersAccess entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UsersAccesses(UsersAccess entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsersAccess")]
	public partial class UsersAccess : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _user_id;
		
		private short _access_id;
		
		private EntityRef<Access> _Access;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(short value);
    partial void Onuser_idChanged();
    partial void Onaccess_idChanging(short value);
    partial void Onaccess_idChanged();
    #endregion
		
		public UsersAccess()
		{
			this._Access = default(EntityRef<Access>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short access_id
		{
			get
			{
				return this._access_id;
			}
			set
			{
				if ((this._access_id != value))
				{
					if (this._Access.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onaccess_idChanging(value);
					this.SendPropertyChanging();
					this._access_id = value;
					this.SendPropertyChanged("access_id");
					this.Onaccess_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Access_UsersAccess", Storage="_Access", ThisKey="access_id", OtherKey="access_id", IsForeignKey=true)]
		public Access Access
		{
			get
			{
				return this._Access.Entity;
			}
			set
			{
				Access previousValue = this._Access.Entity;
				if (((previousValue != value) 
							|| (this._Access.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Access.Entity = null;
						previousValue.UsersAccesses.Remove(this);
					}
					this._Access.Entity = value;
					if ((value != null))
					{
						value.UsersAccesses.Add(this);
						this._access_id = value.access_id;
					}
					else
					{
						this._access_id = default(short);
					}
					this.SendPropertyChanged("Access");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UsersAccess", Storage="_User", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UsersAccesses.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UsersAccesses.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(short);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users_vw")]
	public partial class Users_vw
	{
		
		private short _user_id;
		
		private string _user_name;
		
		public Users_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Case_vw")]
	public partial class Case_vw
	{
		
		private long _case_id;
		
		private string _case_customer_name;
		
		private string _case_ID_number;
		
		private System.Nullable<long> _case_customer_number;
		
		private System.Nullable<short> _case_bill_cycle;
		
		private System.Nullable<System.DateTime> _case_bill_date;
		
		private System.Nullable<int> _case_credit_limit;
		
		private System.Nullable<System.DateTime> _case_date;
		
		private string _case_hijri;
		
		private string _case_comment;
		
		private System.Nullable<byte> _case_status;
		
		private string _case_source;
		
		private System.Nullable<short> _case_nationality_id;
		
		private System.Nullable<byte> _case_fraudStatus_id;
		
		private System.Nullable<int> _case_region;
		
		private System.Nullable<decimal> _case_estimated_loss;
		
		private System.Nullable<decimal> _case_actual_loss;
		
		private string _case_bill_hdate;
		
		private string _case_billing_user2;
		
		private System.Nullable<int> _case_disconnected_numbers_count;
		
		private System.Nullable<bool> _bulk_insertion;
		
		private System.Nullable<System.DateTime> _case_Activate_date;
		
		private string _region;
		
		private string _caseStatus_name;
		
		private string _nationality_name;
		
		private string _fraudStatus_name;
		
		private string _case_city;
		
		public Case_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", DbType="BigInt NOT NULL")]
		public long case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this._case_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_customer_name", DbType="NVarChar(200)")]
		public string case_customer_name
		{
			get
			{
				return this._case_customer_name;
			}
			set
			{
				if ((this._case_customer_name != value))
				{
					this._case_customer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_ID_number", DbType="NVarChar(200)")]
		public string case_ID_number
		{
			get
			{
				return this._case_ID_number;
			}
			set
			{
				if ((this._case_ID_number != value))
				{
					this._case_ID_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_customer_number", DbType="BigInt")]
		public System.Nullable<long> case_customer_number
		{
			get
			{
				return this._case_customer_number;
			}
			set
			{
				if ((this._case_customer_number != value))
				{
					this._case_customer_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_cycle", DbType="SmallInt")]
		public System.Nullable<short> case_bill_cycle
		{
			get
			{
				return this._case_bill_cycle;
			}
			set
			{
				if ((this._case_bill_cycle != value))
				{
					this._case_bill_cycle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_bill_date
		{
			get
			{
				return this._case_bill_date;
			}
			set
			{
				if ((this._case_bill_date != value))
				{
					this._case_bill_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_credit_limit", DbType="Int")]
		public System.Nullable<int> case_credit_limit
		{
			get
			{
				return this._case_credit_limit;
			}
			set
			{
				if ((this._case_credit_limit != value))
				{
					this._case_credit_limit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_date
		{
			get
			{
				return this._case_date;
			}
			set
			{
				if ((this._case_date != value))
				{
					this._case_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_hijri", DbType="NVarChar(200)")]
		public string case_hijri
		{
			get
			{
				return this._case_hijri;
			}
			set
			{
				if ((this._case_hijri != value))
				{
					this._case_hijri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_comment", DbType="NVarChar(MAX)")]
		public string case_comment
		{
			get
			{
				return this._case_comment;
			}
			set
			{
				if ((this._case_comment != value))
				{
					this._case_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_status", DbType="TinyInt")]
		public System.Nullable<byte> case_status
		{
			get
			{
				return this._case_status;
			}
			set
			{
				if ((this._case_status != value))
				{
					this._case_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_source", DbType="NVarChar(200)")]
		public string case_source
		{
			get
			{
				return this._case_source;
			}
			set
			{
				if ((this._case_source != value))
				{
					this._case_source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_nationality_id", DbType="SmallInt")]
		public System.Nullable<short> case_nationality_id
		{
			get
			{
				return this._case_nationality_id;
			}
			set
			{
				if ((this._case_nationality_id != value))
				{
					this._case_nationality_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_fraudStatus_id", DbType="TinyInt")]
		public System.Nullable<byte> case_fraudStatus_id
		{
			get
			{
				return this._case_fraudStatus_id;
			}
			set
			{
				if ((this._case_fraudStatus_id != value))
				{
					this._case_fraudStatus_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_region", DbType="Int")]
		public System.Nullable<int> case_region
		{
			get
			{
				return this._case_region;
			}
			set
			{
				if ((this._case_region != value))
				{
					this._case_region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_estimated_loss", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> case_estimated_loss
		{
			get
			{
				return this._case_estimated_loss;
			}
			set
			{
				if ((this._case_estimated_loss != value))
				{
					this._case_estimated_loss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_actual_loss", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> case_actual_loss
		{
			get
			{
				return this._case_actual_loss;
			}
			set
			{
				if ((this._case_actual_loss != value))
				{
					this._case_actual_loss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_bill_hdate", DbType="NVarChar(200)")]
		public string case_bill_hdate
		{
			get
			{
				return this._case_bill_hdate;
			}
			set
			{
				if ((this._case_bill_hdate != value))
				{
					this._case_bill_hdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_billing_user2", DbType="NVarChar(200)")]
		public string case_billing_user2
		{
			get
			{
				return this._case_billing_user2;
			}
			set
			{
				if ((this._case_billing_user2 != value))
				{
					this._case_billing_user2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_disconnected_numbers_count", DbType="Int")]
		public System.Nullable<int> case_disconnected_numbers_count
		{
			get
			{
				return this._case_disconnected_numbers_count;
			}
			set
			{
				if ((this._case_disconnected_numbers_count != value))
				{
					this._case_disconnected_numbers_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bulk_insertion", DbType="Bit")]
		public System.Nullable<bool> bulk_insertion
		{
			get
			{
				return this._bulk_insertion;
			}
			set
			{
				if ((this._bulk_insertion != value))
				{
					this._bulk_insertion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_Activate_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_Activate_date
		{
			get
			{
				return this._case_Activate_date;
			}
			set
			{
				if ((this._case_Activate_date != value))
				{
					this._case_Activate_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caseStatus_name", DbType="NVarChar(100)")]
		public string caseStatus_name
		{
			get
			{
				return this._caseStatus_name;
			}
			set
			{
				if ((this._caseStatus_name != value))
				{
					this._caseStatus_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string nationality_name
		{
			get
			{
				return this._nationality_name;
			}
			set
			{
				if ((this._nationality_name != value))
				{
					this._nationality_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_name", DbType="NVarChar(100)")]
		public string fraudStatus_name
		{
			get
			{
				return this._fraudStatus_name;
			}
			set
			{
				if ((this._fraudStatus_name != value))
				{
					this._fraudStatus_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_city", DbType="NVarChar(200)")]
		public string case_city
		{
			get
			{
				return this._case_city;
			}
			set
			{
				if ((this._case_city != value))
				{
					this._case_city = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaseStatus_vw")]
	public partial class CaseStatus_vw
	{
		
		private byte _caseStatus_id;
		
		private string _caseStatus_name;
		
		public CaseStatus_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caseStatus_id", AutoSync=AutoSync.Always, DbType="TinyInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public byte caseStatus_id
		{
			get
			{
				return this._caseStatus_id;
			}
			set
			{
				if ((this._caseStatus_id != value))
				{
					this._caseStatus_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caseStatus_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string caseStatus_name
		{
			get
			{
				return this._caseStatus_name;
			}
			set
			{
				if ((this._caseStatus_name != value))
				{
					this._caseStatus_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cities_vw")]
	public partial class Cities_vw
	{
		
		private int _ID;
		
		private string _Name;
		
		public Cities_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConnectionDomains_vw")]
	public partial class ConnectionDomains_vw
	{
		
		private int _ID;
		
		private string _Name;
		
		public ConnectionDomains_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FraudStatus_vw")]
	public partial class FraudStatus_vw
	{
		
		private byte _fraudStatus_id;
		
		private string _fraudStatus_name;
		
		public FraudStatus_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_id", AutoSync=AutoSync.Always, DbType="TinyInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public byte fraudStatus_id
		{
			get
			{
				return this._fraudStatus_id;
			}
			set
			{
				if ((this._fraudStatus_id != value))
				{
					this._fraudStatus_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudStatus_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string fraudStatus_name
		{
			get
			{
				return this._fraudStatus_name;
			}
			set
			{
				if ((this._fraudStatus_name != value))
				{
					this._fraudStatus_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FraudTypes_vw")]
	public partial class FraudTypes_vw
	{
		
		private short _fraudType_id;
		
		private string _fraudType_name;
		
		public FraudTypes_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_id", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short fraudType_id
		{
			get
			{
				return this._fraudType_id;
			}
			set
			{
				if ((this._fraudType_id != value))
				{
					this._fraudType_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string fraudType_name
		{
			get
			{
				return this._fraudType_name;
			}
			set
			{
				if ((this._fraudType_name != value))
				{
					this._fraudType_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GSM_vw")]
	public partial class GSM_vw
	{
		
		private byte _gsm_id;
		
		private string _gsm_name;
		
		public GSM_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_id", AutoSync=AutoSync.Always, DbType="TinyInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public byte gsm_id
		{
			get
			{
				return this._gsm_id;
			}
			set
			{
				if ((this._gsm_id != value))
				{
					this._gsm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string gsm_name
		{
			get
			{
				return this._gsm_name;
			}
			set
			{
				if ((this._gsm_name != value))
				{
					this._gsm_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nationality_vw")]
	public partial class Nationality_vw
	{
		
		private short _nationality_id;
		
		private string _nationality_name;
		
		public Nationality_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_id", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short nationality_id
		{
			get
			{
				return this._nationality_id;
			}
			set
			{
				if ((this._nationality_id != value))
				{
					this._nationality_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string nationality_name
		{
			get
			{
				return this._nationality_name;
			}
			set
			{
				if ((this._nationality_name != value))
				{
					this._nationality_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regions_vw")]
	public partial class Regions_vw
	{
		
		private int _ID;
		
		private string _Name;
		
		public Regions_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.case_line_vw")]
	public partial class case_line_vw
	{
		
		private long _service_no;
		
		private System.Nullable<long> _account_no;
		
		private System.Nullable<decimal> _amount;
		
		private System.Nullable<long> _case_id;
		
		private System.Nullable<byte> _case_gsm_id;
		
		private System.Nullable<short> _case_fraudType_id;
		
		private System.Nullable<short> _case_user_id;
		
		private string _case_line_billing_user;
		
		private string _gsm_name;
		
		private string _fraudType_name;
		
		private string _user_name;
		
		private string _case_line_note_intractive;
		
		private string _case_line_descreption;
		
		private System.Nullable<short> _case_line_connection_domain;
		
		private System.Nullable<System.DateTime> _case_line_activate_date;
		
		private string _case_line_hijri;
		
		private System.Nullable<System.DateTime> _case_line_date;
		
		private string _Expr1;
		
		private string _Name;
		
		public case_line_vw()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_no", DbType="BigInt NOT NULL")]
		public long service_no
		{
			get
			{
				return this._service_no;
			}
			set
			{
				if ((this._service_no != value))
				{
					this._service_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_no", DbType="BigInt")]
		public System.Nullable<long> account_no
		{
			get
			{
				return this._account_no;
			}
			set
			{
				if ((this._account_no != value))
				{
					this._account_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this._amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", DbType="BigInt")]
		public System.Nullable<long> case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this._case_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_gsm_id", DbType="TinyInt")]
		public System.Nullable<byte> case_gsm_id
		{
			get
			{
				return this._case_gsm_id;
			}
			set
			{
				if ((this._case_gsm_id != value))
				{
					this._case_gsm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_fraudType_id", DbType="SmallInt")]
		public System.Nullable<short> case_fraudType_id
		{
			get
			{
				return this._case_fraudType_id;
			}
			set
			{
				if ((this._case_fraudType_id != value))
				{
					this._case_fraudType_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_user_id", DbType="SmallInt")]
		public System.Nullable<short> case_user_id
		{
			get
			{
				return this._case_user_id;
			}
			set
			{
				if ((this._case_user_id != value))
				{
					this._case_user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_billing_user", DbType="NChar(100)")]
		public string case_line_billing_user
		{
			get
			{
				return this._case_line_billing_user;
			}
			set
			{
				if ((this._case_line_billing_user != value))
				{
					this._case_line_billing_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gsm_name", DbType="NVarChar(200)")]
		public string gsm_name
		{
			get
			{
				return this._gsm_name;
			}
			set
			{
				if ((this._gsm_name != value))
				{
					this._gsm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fraudType_name", DbType="NVarChar(200)")]
		public string fraudType_name
		{
			get
			{
				return this._fraudType_name;
			}
			set
			{
				if ((this._fraudType_name != value))
				{
					this._fraudType_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_note_intractive", DbType="NVarChar(2000)")]
		public string case_line_note_intractive
		{
			get
			{
				return this._case_line_note_intractive;
			}
			set
			{
				if ((this._case_line_note_intractive != value))
				{
					this._case_line_note_intractive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_descreption", DbType="NVarChar(2000)")]
		public string case_line_descreption
		{
			get
			{
				return this._case_line_descreption;
			}
			set
			{
				if ((this._case_line_descreption != value))
				{
					this._case_line_descreption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_connection_domain", DbType="SmallInt")]
		public System.Nullable<short> case_line_connection_domain
		{
			get
			{
				return this._case_line_connection_domain;
			}
			set
			{
				if ((this._case_line_connection_domain != value))
				{
					this._case_line_connection_domain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_activate_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> case_line_activate_date
		{
			get
			{
				return this._case_line_activate_date;
			}
			set
			{
				if ((this._case_line_activate_date != value))
				{
					this._case_line_activate_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_hijri", DbType="NVarChar(200)")]
		public string case_line_hijri
		{
			get
			{
				return this._case_line_hijri;
			}
			set
			{
				if ((this._case_line_hijri != value))
				{
					this._case_line_hijri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_line_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> case_line_date
		{
			get
			{
				return this._case_line_date;
			}
			set
			{
				if ((this._case_line_date != value))
				{
					this._case_line_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NChar(100)")]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
